<?php

use App\Http\Controllers\Api\Admin\ContentController as AdminContentController;
use App\Http\Controllers\Api\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Api\Admin\DemoDataController as AdminDemoDataController;
use App\Http\Controllers\Api\Admin\DeploymentController as AdminDeploymentController;
use App\Http\Controllers\Api\Admin\EventRegistrationController as AdminEventRegistrationController;
use App\Http\Controllers\Api\Admin\MediaController as AdminMediaController;
use App\Http\Controllers\Api\Admin\SupportController as AdminSupportController;
use App\Http\Controllers\Api\Admin\VerificationController as AdminVerificationController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BookingController;
use App\Http\Controllers\Api\CurrencyController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\HomeController;
use App\Http\Controllers\Api\LiveChatController;
use App\Http\Controllers\Api\LiveChatInboundMailController;
use App\Http\Controllers\Api\MediaDownloadController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\Provider\BookingController as ProviderBookingController;
use App\Http\Controllers\Api\Provider\BusinessController as ProviderBusinessController;
use App\Http\Controllers\Api\Provider\CommunityPostController as ProviderCommunityPostController;
use App\Http\Controllers\Api\Provider\ContentCalendarController as ProviderContentCalendarController;
use App\Http\Controllers\Api\Provider\DashboardController as ProviderDashboardController;
use App\Http\Controllers\Api\Provider\LiveChatController as ProviderLiveChatController;
use App\Http\Controllers\Api\Provider\ScheduleController as ProviderScheduleController;
use App\Http\Controllers\Api\Provider\ServiceController as ProviderServiceController;
use App\Http\Controllers\Api\Provider\SupportController as ProviderSupportController;
use App\Http\Controllers\Api\ProviderDirectoryController;
use App\Http\Controllers\Api\PublicContentController;
use App\Http\Controllers\Api\StatusController;
use App\Http\Controllers\Api\SubscriptionController;
use App\Http\Controllers\Api\UploadController;
use Illuminate\Support\Facades\Route;

Route::get('/status', StatusController::class);

Route::prefix('auth')->group(function (): void {
    Route::post('/register', [AuthController::class, 'register'])->middleware('throttle:registration');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:password-reset');
    Route::post('/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:password-reset');
});

Route::get('/email/verify/{id}/{hash}', [AuthController::class, 'verifyEmail'])
    ->middleware(['throttle:sensitive'])->name('verification.verify');
Route::get('/auth/email-change/{user}/{token}', [AuthController::class, 'verifyEmailChange'])
    ->middleware(['signed', 'throttle:sensitive'])->name('email-change.verify');

Route::get('/home', HomeController::class);
Route::get('/currencies', [CurrencyController::class, 'index']);
Route::get('/subscription-plans', [SubscriptionController::class, 'plans']);
Route::get('/provider-categories', [ProviderDirectoryController::class, 'categories']);
Route::get('/providers', [ProviderDirectoryController::class, 'index']);
Route::get('/providers/{provider}', [ProviderDirectoryController::class, 'show']);
Route::get('/providers/{provider}/services', [ProviderDirectoryController::class, 'services']);
Route::get('/providers/{provider}/availability', [ProviderDirectoryController::class, 'availability']);
Route::get('/providers/{provider}/reviews', [ProviderDirectoryController::class, 'reviews']);
Route::post('/providers/{provider}/contact', [ProviderDirectoryController::class, 'contact'])->middleware('throttle:public-form');
Route::get('/news', [PublicContentController::class, 'news']);
Route::get('/news/{news:slug}', [PublicContentController::class, 'showNews']);
Route::get('/events', [PublicContentController::class, 'events']);
Route::get('/events/{event:slug}', [PublicContentController::class, 'showEvent']);
Route::post('/events/{event:slug}/registrations', [PublicContentController::class, 'registerForEvent'])->middleware('throttle:public-form');
Route::get('/opportunities', [PublicContentController::class, 'opportunities']);
Route::get('/opportunities/{opportunity}', [PublicContentController::class, 'showOpportunity']);
Route::get('/community-posts', [PublicContentController::class, 'community']);
Route::get('/community-posts/{communityPost}', [PublicContentController::class, 'showCommunity']);
Route::post('/community-posts/{communityPost}/shares', [PublicContentController::class, 'shareCommunity'])->middleware('throttle:public-form');
Route::post('/community-posts/{communityPost}/reports', [PublicContentController::class, 'reportCommunity'])->middleware('throttle:public-form');
Route::post('/newsletter/subscribe', [PublicContentController::class, 'subscribe'])->middleware('throttle:public-form');
Route::post('/mailchimp/webhook', [SubscriptionController::class, 'mailchimpWebhook'])->middleware('throttle:public-form');
Route::post('/paystack/webhook', [SubscriptionController::class, 'paystackWebhook']);
Route::post('/paystack/provider-webhook/{paymentAccount}/{token}', [BookingController::class, 'providerPaystackWebhook'])->middleware('throttle:payment');
Route::post('/contact-enquiries', [PublicContentController::class, 'contact'])->middleware('throttle:public-form');
Route::post('/opportunities/{opportunity}/enquiries', [PublicContentController::class, 'enquire'])->middleware('throttle:public-form');
Route::post('/guest-bookings', [BookingController::class, 'guestStore'])->middleware('throttle:public-form');
Route::post('/booking-payments/{payment}/checkout', [BookingController::class, 'checkoutPayment'])->middleware('throttle:payment');
Route::post('/booking-payments/verify', [BookingController::class, 'verifyPayment'])->middleware('throttle:payment');
Route::post('/providers/{provider}/chat/conversations', [LiveChatController::class, 'start'])->middleware('throttle:public-form');
Route::get('/live-chat/conversations/{conversation}', [LiveChatController::class, 'show'])->middleware('throttle:chat');
Route::post('/live-chat/conversations/{conversation}/messages', [LiveChatController::class, 'reply'])->middleware('throttle:chat');
Route::post('/live-chat/mail/reply', LiveChatInboundMailController::class)->middleware('throttle:chat');

Route::middleware(['auth:sanctum', 'active'])->group(function (): void {
    Route::get('/media/{media}/download', MediaDownloadController::class)->middleware('throttle:api');
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::put('/auth/password', [AuthController::class, 'updatePassword'])->middleware('throttle:sensitive');
    Route::post('/auth/email-change', [AuthController::class, 'requestEmailChange'])->middleware('throttle:sensitive');
    Route::delete('/auth/account', [AuthController::class, 'destroyAccount'])->middleware('throttle:sensitive');
    Route::post('/email/verification-notification', [AuthController::class, 'sendVerification'])->middleware('throttle:email-verification');
    Route::get('/auth/two-factor', [AuthController::class, 'twoFactorStatus']);
    Route::post('/auth/two-factor/enable', [AuthController::class, 'enableTwoFactor'])->middleware('throttle:sensitive');
    Route::post('/auth/two-factor/confirm', [AuthController::class, 'confirmTwoFactor'])->middleware('throttle:sensitive');
    Route::post('/auth/two-factor/recovery-codes', [AuthController::class, 'regenerateRecoveryCodes'])->middleware('throttle:sensitive');
    Route::post('/auth/two-factor/disable', [AuthController::class, 'disableTwoFactor'])->middleware('throttle:sensitive');

    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::patch('/notifications/{id}/read', [NotificationController::class, 'read']);
    Route::post('/notifications/read-all', [NotificationController::class, 'readAll']);
    Route::post('/upload', UploadController::class)->middleware(['verified', 'throttle:upload']);
    Route::post('/community-posts/{communityPost}/reactions', [PublicContentController::class, 'reactToCommunity'])->middleware('throttle:public-form');
    Route::post('/community-posts/{communityPost}/comments', [PublicContentController::class, 'commentOnCommunity'])->middleware('throttle:public-form');

    Route::middleware(['role:customer', 'verified'])->group(function (): void {
        Route::get('/bookings', [BookingController::class, 'index']);
        Route::post('/bookings', [BookingController::class, 'store']);
        Route::get('/bookings/{booking}', [BookingController::class, 'show']);
        Route::patch('/bookings/{booking}/cancel', [BookingController::class, 'cancel']);
        Route::post('/providers/{provider}/reviews', [BookingController::class, 'review']);

        Route::get('/customer/dashboard', [CustomerController::class, 'dashboard']);
        Route::get('/customer/bookings', [BookingController::class, 'index']);
        Route::patch('/customer/bookings/{booking}/cancel', [BookingController::class, 'cancel']);
        Route::post('/customer/booking-payments/{payment}/checkout', [BookingController::class, 'checkoutPayment'])->middleware('throttle:payment');
        Route::post('/customer/booking-payments/verify', [BookingController::class, 'verifyPayment'])->middleware('throttle:payment');
        Route::get('/customer/rewards', [CustomerController::class, 'rewards']);
        Route::get('/customer/live-chat', [LiveChatController::class, 'customerIndex']);
        Route::get('/customer/live-chat/{conversation}', [LiveChatController::class, 'customerShow']);
        Route::post('/customer/live-chat/{conversation}/messages', [LiveChatController::class, 'customerReply'])->middleware('throttle:chat');
        Route::get('/customer/saved-providers', [CustomerController::class, 'saved']);
        Route::post('/customer/saved-providers/{provider}', [CustomerController::class, 'save']);
        Route::delete('/customer/saved-providers/{provider}', [CustomerController::class, 'unsave']);
    });

    Route::prefix('provider')->middleware('role:provider')->group(function (): void {
        Route::post('/onboarding', [ProviderDashboardController::class, 'completeOnboarding'])->middleware('verified');
        Route::middleware('verified')->group(function (): void {
            Route::get('/support', [ProviderSupportController::class, 'index']);
            Route::post('/support', [ProviderSupportController::class, 'store'])->middleware('throttle:public-form');
            Route::get('/support/{ticket}', [ProviderSupportController::class, 'show']);
            Route::post('/support/{ticket}/messages', [ProviderSupportController::class, 'reply'])->middleware('throttle:chat');
        });

        Route::middleware(['verified', 'verified.provider'])->group(function (): void {
            Route::get('/dashboard', [ProviderDashboardController::class, 'index']);
            Route::get('/profile', [ProviderDashboardController::class, 'profile']);
            Route::post('/profile', [ProviderDashboardController::class, 'updateProfile'])->middleware('throttle:upload');
            Route::put('/profile', [ProviderDashboardController::class, 'updateProfile']);
            Route::post('/profile/portfolio', [ProviderDashboardController::class, 'uploadPortfolioImage'])->middleware('throttle:upload');
            Route::delete('/profile/portfolio/{portfolioItem}', [ProviderDashboardController::class, 'deletePortfolioImage']);
            Route::get('/verification', [ProviderDashboardController::class, 'verification']);
            Route::post('/verification/files', [ProviderDashboardController::class, 'uploadVerificationFile'])->middleware('throttle:upload');
            Route::post('/verification', [ProviderDashboardController::class, 'submitVerification']);
            Route::get('/subscription', [SubscriptionController::class, 'current']);
            Route::post('/subscription/checkout', [SubscriptionController::class, 'checkout']);
            Route::post('/subscription/verify', [SubscriptionController::class, 'verify']);
            Route::post('/subscription/downgrade', [SubscriptionController::class, 'downgrade']);
            Route::get('/settings', [ProviderBusinessController::class, 'settings']);
            Route::put('/settings', [ProviderBusinessController::class, 'updateSettings']);
        });

        Route::middleware(['paid.provider', 'verified', 'verified.provider'])->group(function (): void {
            Route::get('/analytics', [ProviderDashboardController::class, 'analytics']);
            Route::get('/services', [ProviderServiceController::class, 'index']);
            Route::post('/services', [ProviderServiceController::class, 'store']);
            Route::put('/services/{service}', [ProviderServiceController::class, 'update']);
            Route::delete('/services/{service}', [ProviderServiceController::class, 'destroy']);
            Route::get('/availability', [ProviderScheduleController::class, 'index']);
            Route::put('/availability', [ProviderScheduleController::class, 'update']);
            Route::get('/blocked-dates', [ProviderScheduleController::class, 'blocks']);
            Route::post('/blocked-dates', [ProviderScheduleController::class, 'storeBlock']);
            Route::delete('/blocked-dates/{blockedDate}', [ProviderScheduleController::class, 'destroyBlock']);
            Route::get('/bookings', [ProviderBookingController::class, 'index']);
            Route::post('/bookings/{booking}/chat', [ProviderBookingController::class, 'chat']);
            Route::patch('/bookings/{booking}/status', [ProviderBookingController::class, 'updateStatus']);
            Route::get('/live-chat', [ProviderLiveChatController::class, 'index']);
            Route::get('/live-chat/{conversation}', [ProviderLiveChatController::class, 'show']);
            Route::post('/live-chat/{conversation}/messages', [ProviderLiveChatController::class, 'reply'])->middleware('throttle:chat');
            Route::patch('/live-chat/{conversation}', [ProviderLiveChatController::class, 'update']);
            Route::get('/payments', [ProviderBusinessController::class, 'payments']);
            Route::get('/payment-accounts', [ProviderBusinessController::class, 'paymentAccounts']);
            Route::put('/payment-accounts', [ProviderBusinessController::class, 'updatePaymentAccount']);
            Route::get('/digital-products', [ProviderBusinessController::class, 'products']);
            Route::post('/digital-products', [ProviderBusinessController::class, 'storeProduct']);
            Route::post('/digital-products/{digitalProduct}', [ProviderBusinessController::class, 'updateProduct']);
            Route::put('/digital-products/{digitalProduct}', [ProviderBusinessController::class, 'updateProduct']);
            Route::delete('/digital-products/{digitalProduct}', [ProviderBusinessController::class, 'destroyProduct']);
            Route::get('/content-calendar', [ProviderContentCalendarController::class, 'index']);
            Route::post('/content-calendar', [ProviderContentCalendarController::class, 'store']);
            Route::put('/content-calendar/{contentCalendarItem}', [ProviderContentCalendarController::class, 'update']);
            Route::delete('/content-calendar/{contentCalendarItem}', [ProviderContentCalendarController::class, 'destroy']);
            Route::get('/community-posts', [ProviderCommunityPostController::class, 'index']);
            Route::post('/community-posts', [ProviderCommunityPostController::class, 'store'])->middleware('throttle:public-form');
            Route::post('/community-posts/{communityPost}', [ProviderCommunityPostController::class, 'update'])->middleware('throttle:public-form');
            Route::put('/community-posts/{communityPost}', [ProviderCommunityPostController::class, 'update'])->middleware('throttle:public-form');
            Route::delete('/community-posts/{communityPost}', [ProviderCommunityPostController::class, 'destroy']);
            Route::get('/crm', [ProviderBusinessController::class, 'crm']);
            Route::put('/crm/{customer}', [ProviderBusinessController::class, 'updateCrm']);
            Route::post('/crm/{customer}/activities', [ProviderBusinessController::class, 'storeCrmActivity']);
            Route::patch('/crm/activities/{activity}', [ProviderBusinessController::class, 'updateCrmActivity']);
            Route::get('/loyalty', [ProviderBusinessController::class, 'loyalty']);
            Route::put('/loyalty/settings', [ProviderBusinessController::class, 'updateLoyaltySettings']);
        });
    });

    Route::prefix('admin')->middleware('role:admin')->group(function (): void {
        Route::post('/security/step-up/code', [AuthController::class, 'requestAdminStepUpCode'])->middleware('throttle:sensitive');
        Route::post('/security/step-up', [AuthController::class, 'confirmAdminStepUp'])->middleware('throttle:sensitive');
        Route::get('/dashboard', [AdminDashboardController::class, 'index']);
        Route::get('/activity', [AdminDashboardController::class, 'activity']);
        Route::get('/waitlist', [AdminDashboardController::class, 'waitlist']);
        Route::patch('/subscribers/{subscriber}', [AdminDashboardController::class, 'updateSubscriber']);
        Route::delete('/subscribers/{subscriber}', [AdminDashboardController::class, 'destroySubscriber']);
        Route::get('/waitlist/export', [AdminDashboardController::class, 'exportWaitlist']);
        Route::get('/users', [AdminDashboardController::class, 'users']);
        Route::get('/users/{user}', [AdminDashboardController::class, 'showUser']);
        Route::patch('/users/{user}', [AdminDashboardController::class, 'updateUser']);
        Route::post('/users/{user}/email-change', [AuthController::class, 'requestManagedEmailChange'])->middleware('throttle:sensitive');
        Route::delete('/users/{user}', [AdminDashboardController::class, 'destroyUser'])->middleware('admin.step-up');
        Route::get('/directory', [AdminDashboardController::class, 'directory']);
        Route::get('/providers/{provider}/preview', [ProviderDirectoryController::class, 'adminPreview']);
        Route::patch('/providers/{provider}', [AdminDashboardController::class, 'updateProvider']);
        Route::get('/provider-categories', [AdminDashboardController::class, 'providerCategories']);
        Route::post('/provider-categories', [AdminDashboardController::class, 'storeProviderCategory']);
        Route::patch('/provider-categories/{category}', [AdminDashboardController::class, 'updateProviderCategory']);
        Route::delete('/provider-categories/{category}', [AdminDashboardController::class, 'destroyProviderCategory']);
        Route::get('/verifications', [AdminVerificationController::class, 'index']);
        Route::patch('/verifications/{verification}', [AdminVerificationController::class, 'update']);
        Route::get('/subscriptions', [AdminDashboardController::class, 'subscriptions']);
        Route::get('/support', [AdminSupportController::class, 'index']);
        Route::get('/support/{ticket}', [AdminSupportController::class, 'show']);
        Route::post('/support/{ticket}/messages', [AdminSupportController::class, 'reply'])->middleware('throttle:chat');
        Route::patch('/support/{ticket}', [AdminSupportController::class, 'update']);
        Route::get('/subscription-plans', [SubscriptionController::class, 'adminPlans']);
        Route::put('/subscription-plans/{plan}', [SubscriptionController::class, 'updateAdminPlan']);
        Route::get('/payment-settings/paystack', [SubscriptionController::class, 'adminPaystackSettings']);
        Route::put('/payment-settings/paystack', [SubscriptionController::class, 'updateAdminPaystackSettings'])->middleware('admin.step-up');
        Route::get('/payment-settings/stripe', [SubscriptionController::class, 'adminStripeSettings']);
        Route::put('/payment-settings/stripe', [SubscriptionController::class, 'updateAdminStripeSettings'])->middleware('admin.step-up');
        Route::get('/payment-settings/gateway', [SubscriptionController::class, 'adminPaymentGatewaySettings']);
        Route::put('/payment-settings/gateway', [SubscriptionController::class, 'updateAdminPaymentGatewaySettings'])->middleware('admin.step-up');
        Route::get('/settings/branding', [SubscriptionController::class, 'adminBrandingSettings']);
        Route::put('/settings/branding', [SubscriptionController::class, 'updateAdminBrandingSettings']);
        Route::get('/settings/currencies', [SubscriptionController::class, 'adminCurrencySettings']);
        Route::put('/settings/currencies', [SubscriptionController::class, 'updateAdminCurrencySettings']);
        Route::post('/settings/currencies/fetch-rates', [SubscriptionController::class, 'fetchCurrencyRates'])->middleware('throttle:sensitive');
        Route::get('/settings/features', [SubscriptionController::class, 'adminFeatureSettings']);
        Route::put('/settings/features', [SubscriptionController::class, 'updateAdminFeatureSettings']);
        Route::get('/settings/hero-images', [SubscriptionController::class, 'adminHeroImages']);
        Route::post('/settings/hero-images/upload', [SubscriptionController::class, 'uploadAdminHeroImage']);
        Route::put('/settings/hero-images', [SubscriptionController::class, 'updateAdminHeroImages']);
        Route::get('/settings/twilio', [SubscriptionController::class, 'adminTwilioSettings']);
        Route::put('/settings/twilio', [SubscriptionController::class, 'updateAdminTwilioSettings'])->middleware('admin.step-up');
        Route::post('/settings/twilio/test', [SubscriptionController::class, 'testAdminTwilio'])->middleware(['throttle:sensitive', 'admin.step-up']);
        Route::get('/settings/smtp', [SubscriptionController::class, 'adminSmtpSettings']);
        Route::put('/settings/smtp', [SubscriptionController::class, 'updateAdminSmtpSettings'])->middleware('admin.step-up');
        Route::post('/settings/smtp/test', [SubscriptionController::class, 'testAdminSmtp'])->middleware(['throttle:sensitive', 'admin.step-up']);
        Route::post('/settings/email-notifications/test', [SubscriptionController::class, 'testAdminEmailNotification'])->middleware('throttle:sensitive');
        Route::get('/settings/mailchimp', [SubscriptionController::class, 'adminMailchimpSettings']);
        Route::put('/settings/mailchimp', [SubscriptionController::class, 'updateAdminMailchimpSettings'])->middleware('admin.step-up');
        Route::post('/settings/mailchimp/test', [SubscriptionController::class, 'testAdminMailchimp'])->middleware(['throttle:sensitive', 'admin.step-up']);
        Route::post('/settings/mailchimp/sync', [SubscriptionController::class, 'syncAdminMailchimp'])->middleware(['throttle:sensitive', 'admin.step-up']);
        Route::get('/settings/deployment', [AdminDeploymentController::class, 'status']);
        Route::post('/settings/deployment/run', [AdminDeploymentController::class, 'run'])->middleware(['throttle:sensitive', 'admin.step-up']);
        Route::post('/settings/cache/clear', [AdminDeploymentController::class, 'clearCache'])->middleware(['throttle:sensitive', 'admin.step-up']);
        Route::get('/demo-data', [AdminDemoDataController::class, 'status']);
        Route::post('/demo-data/populate', [AdminDemoDataController::class, 'populate'])->middleware('admin.step-up');
        Route::delete('/demo-data', [AdminDemoDataController::class, 'clear'])->middleware('admin.step-up');

        Route::get('/media', [AdminMediaController::class, 'index']);
        Route::post('/media', [AdminMediaController::class, 'store'])->middleware('throttle:upload');
        Route::delete('/media', [AdminMediaController::class, 'destroy']);
        Route::get('/news', [AdminContentController::class, 'news']);
        Route::post('/news', [AdminContentController::class, 'storeNews']);
        Route::get('/news/{news}', [AdminContentController::class, 'showNews']);
        Route::put('/news/{news}', [AdminContentController::class, 'updateNews']);
        Route::delete('/news/{news}', [AdminContentController::class, 'destroyNews']);
        Route::get('/events', [AdminContentController::class, 'events']);
        Route::post('/events', [AdminContentController::class, 'storeEvent']);
        Route::get('/events/{event}/registrations/export', [AdminEventRegistrationController::class, 'export']);
        Route::get('/events/{event}', [AdminContentController::class, 'showEvent']);
        Route::put('/events/{event}', [AdminContentController::class, 'updateEvent']);
        Route::delete('/events/{event}', [AdminContentController::class, 'destroyEvent']);
        Route::get('/event-registrations/events', [AdminEventRegistrationController::class, 'events']);
        Route::get('/event-registrations', [AdminEventRegistrationController::class, 'index']);
        Route::patch('/event-registrations/{registration}', [AdminEventRegistrationController::class, 'update']);
        Route::delete('/event-registrations/{registration}', [AdminEventRegistrationController::class, 'destroy']);
        Route::get('/community-posts', [AdminContentController::class, 'community']);
        Route::post('/community-posts', [AdminContentController::class, 'storeCommunity']);
        Route::get('/community-posts/{communityPost}', [AdminContentController::class, 'showCommunity']);
        Route::get('/community-posts/{communityPost}/preview', [AdminContentController::class, 'previewCommunity']);
        Route::put('/community-posts/{communityPost}', [AdminContentController::class, 'updateCommunity']);
        Route::delete('/community-posts/{communityPost}', [AdminContentController::class, 'destroyCommunity']);
        Route::get('/community-reports', [AdminContentController::class, 'communityReports']);
        Route::patch('/community-reports/{report}', [AdminContentController::class, 'updateCommunityReport']);
        Route::get('/opportunities', [AdminContentController::class, 'opportunities']);
        Route::post('/opportunities', [AdminContentController::class, 'storeOpportunity']);
        Route::get('/opportunities/{opportunity}', [AdminContentController::class, 'showOpportunity']);
        Route::put('/opportunities/{opportunity}', [AdminContentController::class, 'updateOpportunity']);
        Route::delete('/opportunities/{opportunity}', [AdminContentController::class, 'destroyOpportunity']);
        Route::get('/opportunity-enquiries', [AdminContentController::class, 'enquiries']);
        Route::patch('/opportunity-enquiries/{enquiry}', [AdminContentController::class, 'updateEnquiry']);
        Route::get('/announcements', [AdminContentController::class, 'announcements']);
        Route::post('/announcements', [AdminContentController::class, 'storeAnnouncement']);
        Route::put('/announcements/{announcement}', [AdminContentController::class, 'updateAnnouncement']);
        Route::delete('/announcements/{announcement}', [AdminContentController::class, 'destroyAnnouncement']);
    });
});
