import { Avatar, Card, EmptyState, ErrorState, LoadingBlock, PageHeader, StatCard, formatDate, useApiResource } from '../../components/dashboard';

const normalize = (value, key) => Array.isArray(value) ? value : value?.[key] ?? value?.data ?? [];

export default function CustomerRewardsPage() {
    const resource = useApiResource('/customer/rewards', {});
    const data = resource.data ?? {};
    const balances = normalize(data, 'balances').length ? normalize(data, 'balances') : normalize(data, 'rewards');
    const history = normalize(data, 'history').length && !Array.isArray(data)
        ? normalize(data, 'history')
        : balances.flatMap((balance) => (balance.transactions ?? []).map((transaction) => ({ ...transaction, provider: balance.provider })));
    const total = data.total_points ?? balances.reduce((sum, item) => sum + Number(item.points ?? 0), 0);
    return <div className="space-y-6"><PageHeader description="Points are tracked separately for each professional you visit." eyebrow="Loyalty" title="My rewards" />{resource.error && <ErrorState message={resource.error} onRetry={resource.reload} />}<div className="grid gap-4 sm:grid-cols-3"><StatCard icon="loyalty" label="Total points" tone="rose" value={Number(total).toLocaleString()} /><StatCard icon="profile" label="Reward programmes" tone="plum" value={balances.length} /><StatCard icon="booking" label="Activities" tone="sky" value={history.length} /></div>{resource.loading ? <LoadingBlock rows={5} /> : <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Card><h2 className="mb-4 font-bold text-slate-950">Balances by provider</h2>{balances.length ? <div className="space-y-3">{balances.map((item) => { const provider = item.provider?.user ?? item.provider ?? {}; return <div className="flex items-center gap-3 rounded-2xl border border-slate-100 p-3" key={item.id}><Avatar name={provider.name} src={item.provider?.profile_photo ?? provider.profile_photo} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900">{provider.name}</p><p className="text-xs text-slate-400">{item.provider?.profession}</p></div><p className="font-bold text-fuchsia-700">{Number(item.points ?? 0).toLocaleString()} pts</p></div>; })}</div> : <EmptyState description="Complete appointments with participating providers to earn points." icon="loyalty" title="No points yet" />}</Card><Card><h2 className="mb-4 font-bold text-slate-950">Points activity</h2>{history.length ? <div className="divide-y divide-slate-100">{history.map((item) => <div className="flex items-center gap-3 py-3" key={item.id}><span className={`grid size-9 place-items-center rounded-xl text-sm font-bold ${Number(item.points) >= 0 ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{Number(item.points) >= 0 ? '+' : '−'}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-800">{item.reason ?? 'Points update'}</p><p className="text-xs text-slate-400">{formatDate(item.created_at)}</p></div><p className="font-bold text-slate-900">{Number(item.points) > 0 ? '+' : ''}{item.points}</p></div>)}</div> : <EmptyState description="Changes to your point balances will appear here." icon="analytics" title="No reward activity" />}</Card></div>}</div>;
}
