import { Link } from 'react-router-dom';
import { Avatar, Button, Card, CardHeader, EmptyState, ErrorState, LoadingBlock, PageHeader, StatCard, StatusBadge, formatDate, useApiResource } from '../../components/dashboard';

const list = (value) => Array.isArray(value) ? value : value?.data ?? [];

export default function AdminDashboardPage() {
    const resource = useApiResource('/admin/dashboard', {});
    const dashboard = resource.data ?? {};
    const stats = dashboard.stats ?? dashboard.summary ?? {};
    const verifications = list(dashboard.pending_verifications ?? dashboard.verifications);
    const activity = list(dashboard.recent_activity ?? dashboard.recent_users ?? dashboard.users);
    return <div className="space-y-7"><PageHeader description="Monitor platform health and keep the directory trusted." eyebrow="Admin console" title="BeautyPro HQ overview" />{resource.error && <ErrorState message={resource.error} onRetry={resource.reload} />}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon="users" label="Total users" tone="plum" value={stats.users ?? stats.total_users ?? 0} /><StatCard icon="profile" label="Listed providers" tone="sky" value={stats.providers ?? stats.listed_providers ?? 0} /><StatCard icon="shield" label="Awaiting verification" tone="amber" value={stats.pending_verifications ?? verifications.length} /><StatCard icon="booking" label="Bookings this month" tone="emerald" value={stats.monthly_bookings ?? stats.bookings ?? 0} /></div><div className="grid gap-5 xl:grid-cols-[1.35fr_1fr]"><Card><CardHeader action={<Link className="text-sm font-bold text-fuchsia-700" to="/admin/verification">Review all</Link>} description="Oldest requests are shown first." title="Verification queue" />{resource.loading ? <LoadingBlock rows={4} /> : verifications.length ? <div className="space-y-3">{verifications.slice(0, 5).map((request) => { const provider = request.provider ?? {}; const user = provider.user ?? request.user ?? {}; return <div className="flex flex-col gap-3 rounded-2xl border border-slate-100 p-4 sm:flex-row sm:items-center" key={request.id}><Avatar name={user.name} src={provider.profile_photo} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900">{user.name}</p><p className="truncate text-xs text-slate-400">{provider.profession} · {provider.country ?? provider.location}</p></div><p className="text-xs text-slate-400">{formatDate(request.created_at)}</p><StatusBadge status={request.status} /><Link to="/admin/verification"><Button type="button" variant="secondary">Review</Button></Link></div>; })}</div> : <EmptyState description="There are no outstanding provider checks." icon="shield" title="Verification queue is clear" />}</Card><Card><CardHeader title="Recent activity" />{resource.loading ? <LoadingBlock rows={4} /> : activity.length ? <div className="space-y-4">{activity.slice(0, 6).map((item, index) => <div className="flex gap-3" key={item.id ?? index}><span className="mt-1 grid size-8 shrink-0 place-items-center rounded-xl bg-slate-100 text-xs font-bold text-slate-500">{index + 1}</span><div><p className="text-sm font-semibold text-slate-800">{item.description ?? item.message ?? `${item.name ?? 'A member'} joined BeautyPro HQ`}</p><p className="mt-1 text-xs text-slate-400">{formatDate(item.created_at)}</p></div></div>)}</div> : <EmptyState description="Platform activity will appear here." icon="analytics" title="No activity yet" />}</Card></div></div>;
}



